import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <main className="flex flex-col min-h-screen">
          <nav className="bg-transparent py-2 shadow-dark-mild">
            <div className="flex flex-row mx-auto max-w-[95%] md:max-w-[90%] lg:max-w-[80%]">
              <div className="font-montserrat list-style-none me-auto flex flex-row ps-0 text-sm md:text-md">
                <div className="flex-none mb-4 lg:mb-0 lg:pe-2 px-2">
                  <Link href="/">Home</Link>
                </div>
                <div className="flex-none mb-4 lg:mb-0 lg:pe-2 px-2">
                  <Link href="/resume">Resume</Link>
                </div>
              </div>
            </div>
          </nav>
          <div className="h-full flex-grow">
            <div className="flex mx-auto max-w-[95%] mt-4 justify-center md:max-w-[90%] lg:max-w-[80%]">
              {children}
            </div>
          </div>
          <footer className="mt-auto">
            <div className="flex h-24 justify-center items-end pb-3">
              <div className="opacity-45 text-sm md:text-md">Created with NextJS + Tailwind</div>
            </div>
          </footer>
        </main>
      </body>
    </html>
  );
}
