import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <main className="bg-gradient-to-b from-prussian-blue from-30%  to-midnight-green">
          <nav className="bg-indigo-blue py-2 shadow-dark-mild">
            <div className="flex flex-col mx-auto max-w-[90%]">
              <ul className="font-montserrat list-style-none me-auto flex flex-col ps-0 lg:flex-row">
                <li className="mb-4 lg:mb-0 lg:pe-2 px-2">
                  <Link href="/">Home</Link>
                </li>
                <li className="mb-4 lg:mb-0 lg:pe-2 px-2">
                  <Link href="/resume">Resume</Link>
                </li>
              </ul>
            </div>
          </nav>
          <div className="">
            <div className="flex flex-col mx-auto max-w-[80%] mt-4">
              {children}
            </div>
          </div>
          <footer>
            <div className="flex h-24 justify-center items-end pb-3">
              <div className="opacity-45">Created with NextJS</div>
            </div>
          </footer>
        </main>
      </body>
    </html>
  );
}
